[package]
name = "CFGBeast"
version = "2.1.0"
edition = "2024"

[dependencies]
native-windows-gui = "1.0.13"
# Optional, for macro-based UI
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.3+spec-1.1.0"

[build-dependencies]
winresource = "0.1.30"
