[package]
name = "CFGBeast"
version = "0.1.0"
edition = "2024"

[dependencies]
native-windows-gui = "1.0.13"
native-windows-derive = "1.0.5" # Optional, for macro-based UI
walkdir = "2.5.0"

[build-dependencies]
winresource = "0.1.28"
